---
title: "Msc_data_cleaning"
author: "Garland Xie"
date: "July 29, 2018"
output: html_document
---

## Import 

```{r import - libraries, echo=TRUE}
library(magrittr)
library(googlesheets)
library(dplyr)
library(purrr)
library(here)
```

```{r import - weight data via googlesheets}

import_gs <- function(url, ws_name) {
  gs_data <- gs_url(url)
  df <- gs_data %>% gs_read(ws = ws_name)
  
  return(df)
}


msc_weight <- import_gs("https://docs.google.com/spreadsheets/d/1jtiaNA2VG_fwnsMAfH-Bu1JdC0Js7Lod4JqLxoMwbek/edit?usp=sharing", "Weight")
```

## Data cleaning

```{r glimpse - weight, echo=FALSE}
msc_weight %>% glimpse()
```

```{r check 1 - # blocks per session, echo = FALSE}
# check to see if there are 5 blocks and 4 time-stamps within each session 
msc_weight %>% 
  group_by(session, treatment) %>%
  summarize(n_blocks = length(unique(block))) %>%
  arrange(treatment)
```
```{r check 2 - # timestamps per block, echo = FALSE}
# check to see 4 time-stamps (T1, T2, T3, T4) within each block
# per treatment per session

msc_weight %>% 
  group_by(session, treatment, block) %>%
  summarize(n_timestamps = length(unique(period))) %>%
  arrange(treatment)

```


```{r check 3 - # pots per block, echo = FALSE}
# check to see 4 time-stamps (T1, T2, T3, T4) within each block
# per treatment per session

msc_weight %>% 
  group_by(session, treatment, block, period) %>%
  summarize(n_pots = length(unique(pot_ID))) %>%
  arrange(treatment, desc(n_pots))

```


```{r check 4 - duplicate spp per timeperiod, echo = FALSE}
# check to see there are any duplicates values within each time-stamp per block

msc_weight %>%
  group_by(session, block, treatment, period) %>%
  summarize(duplicates = anyDuplicated(pot_ID)) %>%
  arrange(desc(duplicates))
```


```{r check 5 - matching spp values per block, echo = FALSE}
# check to see there are any duplicates values within each time-stamp per block

get_n_spp <- function(df, block_id, trt_id, period_id) {
  
  # nse  
    block_id2  <- quo(block_id)
    trt_id2    <- quo(trt_id)
    period_id2 <- quo(period_id) 
    
  # filter
    df2 <- df %>%
      select(session, block, treatment, period, pot_ID) %>%
      filter(block == !! block_id2 & treatment == !! trt_id2 & period == !! period_id2) %>%
      group_by(pot_ID) %>%
      summarise(count = n(),
                block = block_id,
                trt = trt_id, 
                period = period_id) %>%
      select(block, trt, period, pot_ID, count)
  
  # return           
    return(df2)
}


# ww
clean_b1_ww <- list(df = msc_weight, 
                    block_id = "B1", 
                    trt_id = "WW")

clean_b2_ww <- list(df = msc_weight, 
                    block_id = "B2", 
                    trt_id = "WW")

clean_b3_ww <- list(df = msc_weight, 
                    block_id = "B3", 
                    trt_id = "WW")

clean_b4_ww <- list(df = msc_weight, 
                    block_id = "B4", 
                    trt_id = "WW")

clean_b5_ww <- list(df = msc_weight, 
                    block_id = "B5", 
                    trt_id = "WW")


ls_args_ww <- list(c(clean_b1_ww, period_id = "T1"),
                   c(clean_b1_ww, period_id = "T2"),
                   c(clean_b1_ww, period_id = "T3"),
                   c(clean_b1_ww, period_id = "T4"),
                   c(clean_b2_ww, period_id = "T1"),
                   c(clean_b2_ww, period_id = "T2"),
                   c(clean_b2_ww, period_id = "T3"),
                   c(clean_b2_ww, period_id = "T4"),
                   c(clean_b3_ww, period_id = "T1"),
                   c(clean_b3_ww, period_id = "T2"),
                   c(clean_b3_ww, period_id = "T3"),
                   c(clean_b3_ww, period_id = "T4"),
                   c(clean_b4_ww, period_id = "T1"),
                   c(clean_b4_ww, period_id = "T2"),
                   c(clean_b4_ww, period_id = "T3"),
                   c(clean_b5_ww, period_id = "T4"),
                   c(clean_b5_ww, period_id = "T1"),
                   c(clean_b5_ww, period_id = "T2"),
                   c(clean_b5_ww, period_id = "T3"),
                   c(clean_b5_ww, period_id = "T4"))

# wd
clean_b1_wd <- list(df = msc_weight, 
                    block_id = "B1", 
                    trt_id = "WD")

clean_b2_wd <- list(df = msc_weight, 
                    block_id = "B2", 
                    trt_id = "WD")

clean_b3_wd <- list(df = msc_weight, 
                    block_id = "B3", 
                    trt_id = "WD")

clean_b4_wd <- list(df = msc_weight, 
                    block_id = "B4", 
                    trt_id = "WD")

clean_b5_wd <- list(df = msc_weight, 
                    block_id = "B5", 
                    trt_id = "WD")

ls_args_wd <- list(c(clean_b1_wd, period_id = "T1"),
                   c(clean_b1_wd, period_id = "T2"),
                   c(clean_b1_wd, period_id = "T3"),
                   c(clean_b1_wd, period_id = "T4"),
                   c(clean_b2_wd, period_id = "T1"),
                   c(clean_b2_wd, period_id = "T2"),
                   c(clean_b2_wd, period_id = "T3"),
                   c(clean_b2_wd, period_id = "T4"),
                   c(clean_b3_wd, period_id = "T1"),
                   c(clean_b3_wd, period_id = "T2"),
                   c(clean_b3_wd, period_id = "T3"),
                   c(clean_b3_wd, period_id = "T4"),
                   c(clean_b4_wd, period_id = "T1"),
                   c(clean_b4_wd, period_id = "T2"),
                   c(clean_b4_wd, period_id = "T3"),
                   c(clean_b4_wd, period_id = "T4"),
                   c(clean_b5_wd, period_id = "T1"),
                   c(clean_b5_wd, period_id = "T2"),
                   c(clean_b5_wd, period_id = "T3"),
                   c(clean_b5_wd, period_id = "T4"))


# piling everything into a singe df
invoke_map(get_n_spp, .x = ls_args_ww) %>%
  bind_rows() %>%
  arrange(pot_ID, count, period) 

invoke_map(get_n_spp, .x = ls_args_wd) %>%
  bind_rows() %>%
  filter(count < 8 & block == "B5") %>%
  arrange(pot_ID, period, count) 

```


## Save data!

write.csv(msc_weight, file = here("data/project_data/original", "weight.csv"))


## Session info

```{r session info, echo=FALSE}
sessionInfo()
```